version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '5555:5555'
    environment:
      - MONGODB_URI=mongodb+srv://pasindukandanage1999:6Zb2ojLGxsdzPPEU@eventticketprint.xbnwguy.mongodb.net/?retryWrites=true&w=majority&appName=EventTicketPrint

  frontend:
    build: ./frontend
    ports:
      - '4000:4000'
